#!/bin/bash
set -e

# Configuration
DEPLOYMENTS_DIR="deployments"
PROJECT_ID="${GCP_PROJECT_ID:-$(gcloud config get-value project)}"
ZONE="${GCP_ZONE:-us-east5-a}"
MACHINE_TYPE="${GCP_MACHINE_TYPE:-t2a-standard-2}"
DISK_SIZE="${GCP_DISK_SIZE:-50GB}"
IMAGE_FAMILY="ubuntu-2204-lts"
IMAGE_PROJECT="ubuntu-os-cloud"

if [ -z "$PROJECT_ID" ]; then
    echo "❌ Error: No GCP Project ID found. Please set GCP_PROJECT_ID or configure gcloud."
    exit 1
fi

# Script arguments
COMMAND=$1
VM_NAME=$2

log_msg() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

usage() {
    echo "Usage: $0 {create|update} <vm_name>"
    echo ""
    echo "Commands:"
    echo "  create  - Provisions a new VM and deploys the application"
    echo "  update  - Re-runs the deployment playbook on an existing VM"
    echo ""
    exit 1
}

if [ -z "$COMMAND" ] || [ -z "$VM_NAME" ]; then
    usage
fi

# Validate VM_NAME
if [[ ! "$VM_NAME" =~ ^[a-zA-Z0-9-]+$ ]]; then
    echo "❌ Error: Invalid VM name. Only alphanumeric characters and hyphens are allowed."
    exit 1
fi

VM_DIR="$DEPLOYMENTS_DIR/$VM_NAME"
mkdir -p "$DEPLOYMENTS_DIR"

create_vm() {
    if [ -d "$VM_DIR" ]; then
        echo "⚠️  Deployment '$VM_NAME' configuration already exists in $VM_DIR."
        read -p "Do you want to re-provision/overwrite? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 1
        fi
    fi
    mkdir -p "$VM_DIR"

    log_msg "🚀 Creating VM '$VM_NAME' in project '$PROJECT_ID' (Zone: $ZONE)..."
    log_msg "Executing: gcloud compute instances create $VM_NAME ..."
    gcloud compute instances create "$VM_NAME" \
        --project="$PROJECT_ID" \
        --zone="$ZONE" \
        --machine-type="$MACHINE_TYPE" \
        --image-family="$IMAGE_FAMILY" \
        --image-project="$IMAGE_PROJECT" \
        --boot-disk-size="$DISK_SIZE" \
        --tags=http-server,https-server \
        --metadata=enable-oslogin=TRUE

    log_msg "⏳ Waiting for VM to initialize..."
    sleep 20

    # Get IP address
    log_msg "Fetching VM IP address..."
    IP=$(gcloud compute instances describe "$VM_NAME" --zone="$ZONE" --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
    log_msg "✅ VM Created. Public IP: $IP"

    # Configure SSH
    log_msg "🔑 Updating local SSH configuration via gcloud..."
    gcloud compute config-ssh --project="$PROJECT_ID" --quiet

    # Create Inventory File
    # The host alias generated by gcloud is typically: vmname.zone.projectid
    HOST_ALIAS="$VM_NAME.$ZONE.$PROJECT_ID"
    
    log_msg "📝 Generating inventory file..."
    cat > "$VM_DIR/inventory.ini" <<EOF
[openclaw_hosts]
$HOST_ALIAS
EOF

    # Create Default Vars File if it doesn't exist
    if [ ! -f "$VM_DIR/vars.yml" ]; then
        log_msg "📝 Generating default variables file..."
        cat > "$VM_DIR/vars.yml" <<EOF
openclaw_install_mode: "release"
# openclaw_repo_url: "https://github.com/openclaw/openclaw.git" # Uncomment for dev mode
# openclaw_repo_branch: "main"
tailscale_authkey: "" # Add your tailscale key here
EOF
    fi
    
    log_msg "📂 Deployment configuration saved to $VM_DIR"
}

run_ansible() {
    log_msg "🔄 Starting Ansible Deployment..."
    
    if [ ! -f "$VM_DIR/inventory.ini" ]; then
        log_msg "❌ Error: Inventory file not found at $VM_DIR/inventory.ini"
        exit 1
    fi

    # Ensure requirements are installed
    if [ -f "deployment/requirements.yml" ]; then
        log_msg "📦 Installing Ansible requirements..."
        ansible-galaxy collection install -r deployment/requirements.yml
    fi

    log_msg "▶️  Running Playbook..."
    ansible-playbook -i "$VM_DIR/inventory.ini" deployment/playbook.yml -e "@$VM_DIR/vars.yml"
}

case "$COMMAND" in
    create)
        create_vm
        run_ansible
        ;;
    update)
        if [ ! -d "$VM_DIR" ]; then
            log_msg "❌ Deployment '$VM_NAME' not found in $DEPLOYMENTS_DIR."
            exit 1
        fi
        # Refresh SSH config in case IP changed
        log_msg "🔑 Refreshing SSH configuration..."
        gcloud compute config-ssh --project="$PROJECT_ID" --quiet
        run_ansible
        ;;
    *)
        usage
        ;;
esac
